### ISSUE TITLE
Setup Wartremover

### ISSUE THREAD

**Issue by rexim** [tsoding/Issuestant#24]
### Description

[Wartremover] looks like a nice tool. Let's try it out! It should perform the check on CI, of course. I think while the project is small it should be relatively easy to enforce any kind of linting and static checks.

[Wartremover]: https://github.com/puffnfresh/wartremover

**Comment by rexim** [comment]
Circe macros expand to a pretty hairy code with lots of `asInstanceOf`-s. And Wartremover just freaks out looking at all of that. -_-

**Comment by rexim** [comment]
We are using the fully automatic decoding derivation of circe. Let me see if semi-automatic is not that scary for wartremover.

**Comment by rexim** [comment]
No difference. Well probably with such thing as circe you have no choice but `asInstanceOf`-ing around. Json decoding/encoding is actually a pretty local thing. We can probably isolate it in a single file and exlude that file from the linting.

**Comment by Minoru** [comment]
*Secure* [the code], *Contain* [it in the module], *Protect* [it from the linter]. ForNeVeR will be so-o proud of you!

**Comment by ForNeVeR** [comment]
> probably with such thing as circe you have no choice but `asInstanceOf`-ing around. 

I don't think so. You could create some typed macro constructions on deserializing and use reflection+codegen on serializing. But who am I to challenge the decisions of circe authors; probably my methods won't be good for all cases.
